services:
  - type: web
    name: avatarverse-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn avatar_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: avatar_api.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
    healthCheckPath: /api/
    autoDeploy: true 