# Generated by Django 5.2.3 on 2025-06-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_text', models.CharField(max_length=255)),
                ('style', models.CharField(choices=[('A', 'Comic'), ('B', 'Myatic'), ('C', 'Ethereal')], max_length=1)),
                ('overlay_text', models.CharField(blank=True, max_length=100)),
                ('bg_color', models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11')], default='01', max_length=2)),
                ('svg_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
